//PROJECT TYPES
export const PROJECT_FORM = 'PROJECT_FORM';
export const PROJECTS_GET = 'PROJECTS_GET';
export const PROJECT_ADD = 'PROJECT_ADD';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const DELETE_PROJECT= 'DELETE_PROJECT';
export const PROJECT_ERROR= 'PROJECT_ERROR';

//TASK TYPES
export const PROJECT_TASKS= 'PROJECT_TASKS';
export const ADD_TASK= 'ADD_TASK';
export const VALIDATE_TASK= 'VALIDATE_TASK';
export const DELETE_TASK= 'DELETE_TASK';
export const TASK_STATE= 'TASK_STATE';
export const SELECT_TASK= 'SELECT_TASK';
export const EDIT_TASK= 'EDIT_TASK';
export const CLEAR_TASK_SELECTED= 'CLEAR_TASK_SELECTED';

//ALERT TYPES
export const SHOW_ALERT= 'SHOW_ALERT';
export const HIDE_ALERT= 'HIDE_ALERT';

//AUTH TYPES
export const REGISTRATION_SUCCESSFUL= 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_ERROR= 'REGISTRATION_ERROR';
export const GET_USER= 'GET_USER';
export const LOGIN_SUCCESSFUL= 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const LOGOUT= 'LOGOUT';



